name: check Different Architectures

on: [push]  # create list, to indicate when the workflow will run

env:
  ARTIFACT_NAME: myartifact

jobs:
  armv6 :

    runs-on: ubuntu-18.04

    name: Run the bash script
      run:|
        echo "Rhn the bash script to check the environment"
        sh ./run.sh
