name: check Different Architectures

on: [push]  # create list, to indicate when the workflow will run

env:
  ARTIFACT_NAME: myartifact
  #PATH_OF_SCRIPT: cd .github/workflows

jobs:
  armv6 :

    runs-on: ubuntu-18.04

    name: Builds on ubuntu-18.04 armv6
    steps:
        - name: Checkout the code
          uses: actions/checkout@v2.1.0
        
        - name: Run the bash script
          run: | #when execute the script, I use 'bash ./run.sh' because the 'sh ./run.sh' doesn't have the '[[ ... ]]' testing syntax
            echo "Run the bash script to check the environment"
            cd .github/workflows
            chmod +x run.sh
            bash ./run.sh
        
        - name: Run or Not the branch on Jenkins platform
          if: failure() # that means that the previous run of the script has exit with 1 ==> 'exit 1'
          echo: "The jenkins job won't trigger. I have to check the other option."
        
        # - name: Run on the uraimo action
        #   uses: uraimo/run-on-arch-action@v2
        #   with:
        #     arch: armv6
        #     distro: bullseye

        # - name: Compile the file from the repo
        #   run: |
        #     pwd
        #     ls
        #     g++ -c -Wall -g Main.cpp
        #     g++ -g -o Main.exe Main.o
        #     ./Main.exe

        # - name: Create artifacts
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: ${{env.ARTIFACT_NAME}}
        #     path: .
