name: check Different Architectures

on: [push]  # create list, to indicate when the workflow will run

env:
  ARTIFACT_NAME: myartifact
  #PATH_OF_SCRIPT: cd .github/workflows

jobs:
  armv6 :

    runs-on: ubuntu-latest

    name: Builds on ubuntu-latest for Jenk
    steps:
        - name: Checkout the code
          uses: actions/checkout@v2.1.0

        - name: Run the bash script
          run: |                                                                # when execute the script, I use 'bash ./run.sh' because the 'sh ./run.sh' doesn't have the '[[ ... ]]' testing syntax
            echo "Run the bash script to check the environment"                 # print nice message for the action
            cd .github/workflows                                                # go to the proper path
            chmod +x run.sh                                                     # give access for execution
            echo "SCRIPT_RESULT=$(bash ./run.sh | tail -n 1)" >> $GITHUB_ENV    # store the output of the script to env variable SCRIPT_RESULT

        - name: The jenkins workflow will be triggered
          if: contains(env.SCRIPT_RESULT, 'jenkins')                            # if the env variable contains the word 'jenkins' from the script file, then
          run: echo "YES"                                                       # the proper Jenkins pipeline will be triggered


        # - name: Run on the uraimo action
        #   uses: uraimo/run-on-arch-action@v2
        #   with:
        #     arch: armv6
        #     distro: bullseye

        # - name: Compile the file from the repo
        #   run: |
        #     pwd
        #     ls
        #     g++ -c -Wall -g Main.cpp
        #     g++ -g -o Main.exe Main.o
        #     ./Main.exe

        # - name: Create artifacts
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: ${{env.ARTIFACT_NAME}}
        #     path: .
